export default {
  pageTitle: "Contáctanos",
  pageDescription: "Estamos aquí para ayudar.",
  contactTitle: "Contacta con Calcorp",
  contactDescription: "Estamos aquí para ayudar. Llena el formulario o envía un correo electrónico o llama por teléfono.",
  address: "Ordino, AD300",
  email: "hello@astroshipstarter.com",
  phone: "+1 (987) 4587 899",
  fullNamePlaceholder: "Nombre Completo",
  fullNameFeedback: "Por favor, proporciona tu nombre completo.",
  emailPlaceholder: "Dirección de Correo",
  emailFeedback: "Por favor, proporciona tu dirección de correo.",
  emailInvalidFeedback: "Por favor, proporciona una dirección de correo válida.",
  messagePlaceholder: "Tu Mensaje",
  messageFeedback: "Por favor, ingresa tu mensaje.",
  sendMessageButton: "Enviar Mensaje",
  sendingMessage: "Enviando...",
  successMessage: "¡Tu mensaje ha sido enviado con éxito!",
  errorMessage: "¡Algo salió mal!",
};
