export default {
  pageTitle: "Contacta'ns",
  pageDescription: "Som aquí per ajudar.",
  contactTitle: "Contacta Calcorp",
  contactDescription: "Som aquí per ajudar. Omple el formulari o envia un correu electrònic o truca per telèfon.",
  address: "Ordino AD300",
  email: "calcorp.detail660@simplelogin.com",
  phone: "+376",
  fullNamePlaceholder: "Nom complet",
  fullNameFeedback: "Si us plau, proporciona el teu nom complet.",
  emailPlaceholder: "Adreça de correu",
  emailFeedback: "Si us plau, proporciona la teva adreça de correu.",
  emailInvalidFeedback: "Si us plau, proporciona una adreça de correu vàlida.",
  messagePlaceholder: "El teu missatge",
  messageFeedback: "Si us plau, introdueix el teu missatge.",
  sendMessageButton: "Enviar missatge",
  sendingMessage: "Enviant...",
  successMessage: "El teu missatge s'ha enviat amb èxit!",
  errorMessage: "Alguna cosa ha anat malament!",
};
