export default {
  pageTitle: "Contáctanos",
  pageDescription: "¿En qué podemos ayudarte?",
  contactTitle: "Hablemos",
  contactDescription: "Rellena el formulario o llámanos.",
  address: "Ordino, AD300",
  email: "hola@calcorp.io",
  phone: "+376",
  fullNamePlaceholder: "Nombre Completo",
  fullNameFeedback: "Por favor, proporciona tu nombre completo.",
  emailPlaceholder: "Dirección de Correo",
  emailFeedback: "Por favor, proporciona tu dirección de correo.",
  emailInvalidFeedback: "Por favor, proporciona una dirección de correo válida.",
  messagePlaceholder: "Tu Mensaje",
  messageFeedback: "Por favor, ingresa tu mensaje.",
  sendMessageButton: "Enviar Mensaje",
  sendingMessage: "Enviando...",
  successMessage: "¡Tu mensaje ha sido enviado con éxito!",
  errorMessage: "¡Algo salió mal!",
};
