export default {
  pageTitle: "Contacta'ns",
  pageDescription: "En què et podem ajudar?",
  contactTitle: "Parlem",
  contactDescription: "Omple el formulari o truca'ns.",
  address: "Andorra, Europa",
  email: "hola@calcorp.io",
  phone: "",
  fullNamePlaceholder: "Nom complet",
  fullNameFeedback: "Si us plau, proporciona el teu nom complet.",
  emailPlaceholder: "Adreça de correu",
  emailFeedback: "Si us plau, proporciona la teva adreça de correu.",
  emailInvalidFeedback: "Si us plau, proporciona una adreça de correu vàlida.",
  messagePlaceholder: "El teu missatge",
  messageFeedback: "Si us plau, introdueix el teu missatge.",
  sendMessageButton: "Enviar missatge",
  sendingMessage: "Enviant...",
  successMessage: "El teu missatge s'ha enviat amb èxit!",
  errorMessage: "Alguna cosa ha anat malament!",
};
