export default {
  pageTitle: "Contact",
  pageDescription: "How can we help?",
  contactTitle: "Talk to CalCorp",
  contactDescription: "Fill out the form or drop us a line.",
  address: "Ordino AD300",
  email: "hola@calcorp.io",
  phone: "+376",
  fullNamePlaceholder: "Full Name",
  fullNameFeedback: "Please provide your full name.",
  emailPlaceholder: "Email Address",
  emailFeedback: "Please provide your email address.",
  emailInvalidFeedback: "Please provide a valid email address.",
  messagePlaceholder: "Your Message",
  messageFeedback: "Please enter your message.",
  sendMessageButton: "Send Message",
  sendingMessage: "Sending...",
  successMessage: "Your message has been sent successfully!",
  errorMessage: "Something went wrong!",
};
