export default {
  pageTitle: "Contact",
  pageDescription: "We are here to help.",
  contactTitle: "Contact Astroship",
  contactDescription: "We are here to help. Fill up the form or send email or call phone.",
  address: "Ordino AD300",
  email: "calcorp.detail660@simplelogin.com",
  phone: "+376",
  fullNamePlaceholder: "Full Name",
  fullNameFeedback: "Please provide your full name.",
  emailPlaceholder: "Email Address",
  emailFeedback: "Please provide your email address.",
  emailInvalidFeedback: "Please provide a valid email address.",
  messagePlaceholder: "Your Message",
  messageFeedback: "Please enter your message.",
  sendMessageButton: "Send Message",
  sendingMessage: "Sending...",
  successMessage: "Your message has been sent successfully!",
  errorMessage: "Something went wrong!",
};
